services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
    volumes:
      - .:/app

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
